### ISSUE TITLE
Cache authToken

### ISSUE THREAD

**Issue by Fx4-X** [P1llus/ArcSight-Rest#6]
what about save session by saving the authToken in a file and load it later for new search ?

**Comment by P1llus** [comment]
Saving sessions will unfortunately be outside the scope of a library, and will most likely cause more issues than it fixes, as a wrong implementation will leave hundreds of saved sessions, as they have quite a short timeout.

The saving of the session should happen in the script/application you use the library in, i will see if i can create a way for you to define an already existing session, and if not provided, it will create a new one! Planned for this weekend.

**Comment by P1llus** [comment]
Sorry for the very late responses, been quite some busy months!

I have now done a full rewrite of the library, preparing it to be included in a much larger package with documentation, request examples, implementation examples etc.

I have now pushed a new version 2.0, which is not backward compatible, and it will also be the last commit to this repo, as it has moved to a new location. All information is in the updated README file.

The new version 2.0 will include some examples on caching the authtoken. The only issue you might face is the timeout of the user session, since the library itself should not handle it.
The SDK is now much more generic, which provides more flexibility but also puts a bit more faith on the user
